vich_uploader:
    db_driver: orm

    mappings:
      image:
        uri_prefix: /files/image
        upload_destination: '%kernel.project_dir%/public/files/image'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
